apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: client-a

resources:
  - ../../base

nameSuffix: -client-a

patches:
  - target:
      kind: Deployment
      name: nginx
    path: env-patch.yaml
